### ISSUE TITLE
Андрюха правь ошибки ОЛРЛАГНИУРарРФЫШвгршфГВРШФгпшщфырисолрфсирилилсоифшГВСШГФщшФГРВФЫРВЩШГФСщщрыивщорисрыИОВИСЛЫОРИСОЛВГФПшщсгрщшвгршФГСРОРВФИСРО

### ISSUE THREAD

**Issue by DimaPopkov** [IngCenter/FallSimulator#30]
1.БАГ если выбрать блок и зажать левую кнопку мыши и водить по разным большим блокам ,то
если поставить эти блоки в центр , то появяться все на что вы навели
2.исчезновение:блок выбраный
4.лакиблок был передвинут,но исчез другой,а лакиблок
 остался на том же месте
5.Блоки можно завести в правую часть.
6.не прорисовывается кнопка сохранения
7.спустя 2 минуты появился из неоткуда белый прямоугольник.
8.Если поставить много блоков в одно место и понажимать на правую кнопку мыши по эти блокам, то перемещение их в этом месте и заблокируется.

**Comment by DarkCat09** [comment]
Чё ты написал?

**Comment by DarkCat09** [comment]
НЕПОНЯТНО
