### ISSUE TITLE
баги

### ISSUE THREAD

**Issue by CAHIH** [IngCenter/FallSimulator#31]
1.Во время переноса любого блока его можно перенести на главное изображение блока и уменьшенная версия блока останется его изображение на главном изображении блока.
2.Если любые блоки перенести на одно и тоже место то большая часть блоков исчезнет.
3.Неудобно выходить на кнопку "Q". 
4.Не открывается справка.
5.Если выбранные блоки поставить в одно место и нажать на правую кнопку мыши то все блоки удалятся.
6.Если блок перенести любой блок в правый нижний блок то он не даст тебе там поставить блок.5

**Comment by DarkCat09** [comment]
Спасибо, исправлю...

**Comment by DarkCat09** [comment]
1.Fixed! (Исправлено!)
2.Что?
3.Fixed!
4.Fixed!
5.Can't fix... (Не могу исправить...)
6.Working on this. (Работаю над этим.)

**Comment by DarkCat09** [comment]
2.Всё, понял. Но не нашёл этой ошибки.
6.Пока что не работаю над этим :)
